// Code generated by openapi-generate, DO NOT EDIT.

package httpapi

import (
	"context"

	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/trace"
	"go.uber.org/fx"
	"golang.org/x/oauth2"

	httpclient "github.com/Sokol111/ecommerce-commons/pkg/http/client"
)

const clientName = "tenant-service"

// TokenSecuritySource implements SecuritySource using an oauth2.TokenSource.
type TokenSecuritySource struct {
	source oauth2.TokenSource
}

// NewTokenSecuritySource creates a SecuritySource that delegates to an oauth2.TokenSource.
func NewTokenSecuritySource(source oauth2.TokenSource) *TokenSecuritySource {
	return &TokenSecuritySource{source: source}
}

// BearerAuth returns the bearer token for authentication.
func (s *TokenSecuritySource) BearerAuth(ctx context.Context, _ OperationName) (BearerAuth, error) {
	t, err := s.source.Token()
	if err != nil {
		return BearerAuth{}, err
	}
	return BearerAuth{Token: t.AccessToken}, nil
}

// NewClientModule provides the generated API client for fx DI.
func NewClientModule() fx.Option {
	return fx.Module(clientName+"-client",
		fx.Provide(
			func(
				registry *httpclient.Registry,
				tokenSource oauth2.TokenSource,
				tracerProvider trace.TracerProvider,
				meterProvider metric.MeterProvider,
			) (Invoker, error) {
				httpClient, err := registry.Client(clientName)
				if err != nil {
					return nil, err
				}
				cfg, err := registry.Config(clientName)
				if err != nil {
					return nil, err
				}
				return NewClient(
					cfg.BaseURL,
					NewTokenSecuritySource(tokenSource),
					WithClient(httpClient),
					WithTracerProvider(tracerProvider),
					WithMeterProvider(meterProvider),
				)
			},
		),
	)
}
