// Code generated by openapi-generate, DO NOT EDIT.

package httpapi

import (
	"context"

	"github.com/Sokol111/ecommerce-commons/pkg/security/validation"
)

type securityHandlerAdapter struct {
	handler validation.SecurityHandler
}

// NewSecurityHandlerAdapter creates a SecurityHandler that delegates to a validation.SecurityHandler.
func NewSecurityHandlerAdapter(handler validation.SecurityHandler) SecurityHandler {
	return &securityHandlerAdapter{handler: handler}
}

// HandleBearerAuth handles BearerAuth security.
func (s *securityHandlerAdapter) HandleBearerAuth(ctx context.Context, _ OperationName, t BearerAuth) (context.Context, error) {
	ctx, _, err := s.handler.HandleBearerAuth(ctx, t.Token, t.Roles)
	return ctx, err
}
