// Code generated by openapi-generate, DO NOT EDIT.

package httpapi

import (
	"context"
	"net/http"

	"github.com/knadh/koanf/v2"
	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/trace"
	"go.uber.org/fx"

	httpclient "github.com/Sokol111/ecommerce-commons/pkg/http/client"
	"github.com/Sokol111/ecommerce-commons/pkg/security/token"
)

// TokenSecuritySource implements SecuritySource using a token.Provider.
type TokenSecuritySource struct {
	provider token.Provider
}

// NewTokenSecuritySource creates a SecuritySource that delegates to a token.Provider.
func NewTokenSecuritySource(provider token.Provider) *TokenSecuritySource {
	return &TokenSecuritySource{provider: provider}
}

// BearerAuth returns the bearer token for authentication.
func (s *TokenSecuritySource) BearerAuth(ctx context.Context, _ OperationName) (BearerAuth, error) {
	t, err := s.provider.Token(ctx)
	if err != nil {
		return BearerAuth{}, err
	}
	return BearerAuth{Token: t}, nil
}

// NewClientModule provides the generated API client for fx DI.
func NewClientModule(configPath string) fx.Option {
	return fx.Module(configPath,
		fx.Provide(
			fx.Private,
			func(k *koanf.Koanf) (httpclient.Config, error) {
				return httpclient.LoadConfig(k, configPath)
			},
		),
		fx.Provide(
			fx.Private,
			func(cfg httpclient.Config) (*http.Client, error) {
				return httpclient.New(cfg)
			},
		),
		fx.Provide(
			func(
				httpClient *http.Client,
				cfg httpclient.Config,
				tokenProvider token.Provider,
				tracerProvider trace.TracerProvider,
				meterProvider metric.MeterProvider,
			) (Invoker, error) {
				return NewClient(
					cfg.BaseURL,
					NewTokenSecuritySource(tokenProvider),
					WithClient(httpClient),
					WithTracerProvider(tracerProvider),
					WithMeterProvider(meterProvider),
				)
			},
		),
	)
}
