// Code generated by openapi-generate, DO NOT EDIT.

package httpapi

import (
	"net/http"

	"go.uber.org/fx"
)

// ServerModule provides the ogen HTTP server with security handler for fx DI.
func ServerModule() fx.Option {
	return fx.Options(
		fx.Provide(
			ProvideServer,
			NewSecurityHandlerAdapter,
		),
		fx.Invoke(registerOgenRoutes),
	)
}

func registerOgenRoutes(mux *http.ServeMux, server *Server) {
	mux.Handle("/", server)
}
