// Code generated by openapi-generate, DO NOT EDIT.

package httpapi

import (
	"context"
	"fmt"

	"github.com/Sokol111/ecommerce-commons/pkg/messaging/kafka/consumer"
	commonsmongo "github.com/Sokol111/ecommerce-commons/pkg/persistence/mongo"
	tenant_events "github.com/Sokol111/ecommerce-tenant-service-api/gen/events"
	"go.uber.org/fx"
	"go.uber.org/zap"
)

type tenantEventHandler struct {
	migrator commonsmongo.TenantMigrationRunner
	log      *zap.Logger
}

func newTenantEventHandler(migrator commonsmongo.TenantMigrationRunner, log *zap.Logger) *tenantEventHandler {
	return &tenantEventHandler{migrator: migrator, log: log}
}

func (h *tenantEventHandler) Process(ctx context.Context, event any) error {
	switch evt := event.(type) {
	case *tenant_events.TenantUpdatedEvent:
		return h.handleTenantUpdated(ctx, evt)
	case *tenant_events.TenantDeletedEvent:
		h.log.Warn("tenant deleted event received, manual cleanup may be required",
			zap.String("tenant", evt.Payload.Slug))
		return nil
	default:
		h.log.Warn("unknown tenant event type, skipping", zap.String("type", fmt.Sprintf("%T", event)))
		return fmt.Errorf("unhandled tenant event type: %T: %w", event, consumer.ErrSkipMessage)
	}
}

func (h *tenantEventHandler) handleTenantUpdated(ctx context.Context, evt *tenant_events.TenantUpdatedEvent) error {
	if !evt.Payload.Enabled {
		h.log.Info("tenant disabled, skipping migration", zap.String("tenant", evt.Payload.Slug))
		return nil
	}

	h.log.Info("tenant updated, running migration", zap.String("tenant", evt.Payload.Slug))

	if err := h.migrator.MigrateTenant(ctx, evt.Payload.Slug); err != nil {
		return fmt.Errorf("failed to migrate tenant %q: %w", evt.Payload.Slug, err)
	}

	return nil
}

// TenantEventsModule registers a Kafka consumer for tenant events that runs
// database migrations when new tenants are created or existing ones are updated.
// consumerName must match a consumer entry in the kafka config.
func TenantEventsModule(consumerName string) fx.Option {
	return fx.Options(
		tenant_events.Module(),
		consumer.RegisterHandlerAndConsumer(consumerName, newTenantEventHandler),
	)
}
