// Code generated by openapi-generate, DO NOT EDIT.

package httpapi

import (
	"context"
	"net/http"

	"github.com/knadh/koanf/v2"
	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/trace"
	"go.uber.org/fx"
	"golang.org/x/oauth2"

	httpclient "github.com/Sokol111/ecommerce-commons/pkg/http/client"
)

// TokenSecuritySource implements SecuritySource using an oauth2.TokenSource.
type TokenSecuritySource struct {
	source oauth2.TokenSource
}

// NewTokenSecuritySource creates a SecuritySource that delegates to an oauth2.TokenSource.
func NewTokenSecuritySource(source oauth2.TokenSource) *TokenSecuritySource {
	return &TokenSecuritySource{source: source}
}

// BearerAuth returns the bearer token for authentication.
func (s *TokenSecuritySource) BearerAuth(ctx context.Context, _ OperationName) (BearerAuth, error) {
	t, err := s.source.Token()
	if err != nil {
		return BearerAuth{}, err
	}
	return BearerAuth{Token: t.AccessToken}, nil
}

// NewClientModule provides the generated API client for fx DI.
func NewClientModule(configPath string) fx.Option {
	return fx.Module(configPath,
		fx.Provide(
			fx.Private,
			func(k *koanf.Koanf) (httpclient.Config, error) {
				return httpclient.LoadConfig(k, configPath)
			},
		),
		fx.Provide(
			fx.Private,
			func(cfg httpclient.Config) (*http.Client, error) {
				return httpclient.New(cfg)
			},
		),
		fx.Provide(
			func(
				httpClient *http.Client,
				cfg httpclient.Config,
				tokenSource oauth2.TokenSource,
				tracerProvider trace.TracerProvider,
				meterProvider metric.MeterProvider,
			) (Invoker, error) {
				return NewClient(
					cfg.BaseURL,
					NewTokenSecuritySource(tokenSource),
					WithClient(httpClient),
					WithTracerProvider(tracerProvider),
					WithMeterProvider(meterProvider),
				)
			},
		),
	)
}
