name: Release

on:
  workflow_dispatch:
  push:
    paths:
      - "openapi/openapi.yml"
      - "avro/**"

permissions:
  contents: write
  packages: write

jobs:
  release:
    uses: Sokol111/ecommerce-infrastructure/.github/workflows/api-release.yml@master
