name: Release

on:
  push:
    branches:
      - master
    paths:
      - VERSION
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  release:
    uses: Sokol111/ecommerce-infrastructure/.github/workflows/api-release.yml@master
